# Basic
title: Minfeng Qi
subtitle: Personal Blog
description: Welcome to my Blog
# 头像里面的标题
avatarTitle: Dylan
# 头像里面的描述
avatarDesc: Blockchain / IoT
url: "https://minfengqi.com"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # disqus: 
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo:  
    github: Minfeng-Qi
    zhihu: 
    twitter: 
    mail: minfeng.qi7@gmail.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id:   

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id:  
    host:   


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#

#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: All Articles, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}      
    - {title: Support, description: support, url: '/support'}      
    - {title: About Me, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
